name: Deploy Frontend to Railway

on:
  push:
    branches:
      - main
      - production
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://polito-log-backend.up.railway.app' }}
        run: |
          cd frontend
          npm run build

      - name: Run tests (if available)
        run: |
          cd frontend
          # Add your test command here when tests are implemented
          # npm run test:unit
        continue-on-error: true

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy Frontend to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd frontend
          railway up --service frontend --detach

      - name: Deployment Summary
        run: |
          echo "✅ Frontend deployed successfully to Railway"
          echo "🔗 Service: frontend"
          echo "📦 Branch: ${{ github.ref_name }}"
          echo "🔨 Commit: ${{ github.sha }}"
