name: Deploy Backend to Railway

on:
  push:
    branches:
      - main
      - production
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run tests (if available)
        run: |
          cd backend
          # Add your test command here when tests are implemented
          # pytest tests/
        continue-on-error: true

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy Backend to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd backend
          railway up --service backend --detach

      - name: Run Database Migrations
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd backend
          # Uncomment when migrations are set up
          # railway run --service backend alembic upgrade head
        continue-on-error: true

      - name: Deployment Summary
        run: |
          echo "✅ Backend deployed successfully to Railway"
          echo "🔗 Service: backend"
          echo "📦 Branch: ${{ github.ref_name }}"
          echo "🔨 Commit: ${{ github.sha }}"
